CONFIG_INSTRUMENTATION_MODE_CALLGRAPH_DUMP_ON_FULL=y
# Exclude sys_clock_isr and similar functions as they create overlapping events
CONFIG_INSTRUMENTATION_EXCLUDE_FILE_LIST="drivers/timer/cortex_m_systick.c"

CONFIG_INSTRUMENTATION_DYNAMIC_TRIGGER=n
CONFIG_INSTRUMENTATION_TRIGGER_FUNCTION="main"
CONFIG_INSTRUMENTATION_STOPPER_FUNCTION="main"
