CONFIG_ZPL_INSTRUMENTATION=y
CONFIG_ZPL_TRACE_BACKEND_USB=y

CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_THREAD_STACK_SIZE=4096

CONFIG_INSTRUMENTATION=y
CONFIG_INSTRUMENTATION_MODE_CALLGRAPH_BUFFER_OVERWRITE=n
CONFIG_INSTRUMENTATION_BACKEND_TRACING_CORE=y
CONFIG_INSTRUMENTATION_CTF_TIMER=y
CONFIG_INSTRUMENTATION_DYNAMIC_TRIGGER=n
CONFIG_INSTRUMENTATION_TRIGGER_FUNCTION="main"
CONFIG_INSTRUMENTATION_STOPPER_FUNCTION="main"

CONFIG_TRACING_BACKEND_USB=y
CONFIG_TRACING_ASYNC=y

CONFIG_THREAD_MAX_NAME_LEN=20
