CONFIG_INSTRUMENTATION_BACKEND_UART=y
CONFIG_INSTRUMENTATION_MODE_CALLGRAPH_DUMP_ON_FULL=y

CONFIG_INSTRUMENTATION_DYNAMIC_TRIGGER=n
CONFIG_INSTRUMENTATION_TRIGGER_FUNCTION="main"
CONFIG_INSTRUMENTATION_STOPPER_FUNCTION="main"

CONFIG_ZPL_TRACE_BACKEND_DEBUGGER=y
