CONFIG_INSTRUMENTATION_BACKEND_TRACING_CORE=y

CONFIG_INSTRUMENTATION_DYNAMIC_TRIGGER=n
CONFIG_INSTRUMENTATION_TRIGGER_FUNCTION="main"
CONFIG_INSTRUMENTATION_STOPPER_FUNCTION="main"

CONFIG_THREAD_MAX_NAME_LEN=20
