CONFIG_INSTRUMENTATION=y
CONFIG_INSTRUMENTATION_MODE_CALLGRAPH_BUFFER_OVERWRITE=n

CONFIG_ZPL_RUNTIME_CONFIG_UART=y

CONFIG_ZPL_SAMPLE_TFLM_MODEL="sine"
CONFIG_ZPL_SAMPLE_TFLM_BUFFER_SIZE=8

CONFIG_MAIN_STACK_SIZE=3072
CONFIG_SYS_HEAP_ARRAY_SIZE=4

CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FLOAT_PRINTF=y

CONFIG_ZPL=y
CONFIG_ZPL_TRACE=y
CONFIG_ZPL_MEMORY_PROFILING=y
CONFIG_ZPL_MEMORY_PROFILING_INTERVAL=200
