CONFIG_ZPL_INSTRUMENTATION=y
CONFIG_ZPL_TRACE_BACKEND_DEBUGGER=y

CONFIG_INSTRUMENTATION_TRIGGER_FUNCTION="_ZN4tflm9model_runEv"
CONFIG_INSTRUMENTATION_STOPPER_FUNCTION="_ZN4tflm9model_runEv"

CONFIG_SYS_HEAP_ARRAY_SIZE=4
CONFIG_RAM_TRACING_BUFFER_SIZE=10240

CONFIG_ZPL=y
CONFIG_ZPL_TRACE=y
CONFIG_TRACING_SYNC=y

CONFIG_ZPL_TFLM_PROFILER=y
CONFIG_ZPL_SAMPLE_TFLM_BUFFER_SIZE=10

CONFIG_ZPL_MEMORY_PROFILING=y
CONFIG_ZPL_MEMORY_PROFILING_INTERVAL=5
CONFIG_ZPL_MEMORY_PROFILING_THREAD_PRIORITY=-1

CONFIG_CPU_LOAD=y
CONFIG_ZPL_CPU_LOAD_TRACE=y
CONFIG_ZPL_CPU_LOAD_PROFILING=y
CONFIG_ZPL_CPU_LOAD_PROFILING_INTERVAL=5
CONFIG_ZPL_CPU_LOAD_PROFILING_THREAD_PRIORITY=-1

CONFIG_ZPL_SCOPE_MARKING=y
