CONFIG_ZPL_INSTRUMENTATION=y
CONFIG_ZPL_TRACE_BACKEND_DEBUGGER=y

CONFIG_INSTRUMENTATION_TRIGGER_FUNCTION="model_run"
CONFIG_INSTRUMENTATION_STOPPER_FUNCTION="model_run"

CONFIG_SYS_HEAP_ARRAY_SIZE=4
CONFIG_RAM_TRACING_BUFFER_SIZE=16384

CONFIG_ZPL=y
CONFIG_ZPL_TRACE=y
CONFIG_TRACING_SYNC=y

CONFIG_ZPL_TVM_PROFILER=y
CONFIG_ZPL_TVM_PROFILER_MAX_EVENTS=6
CONFIG_ZPL_TRACE_CTF_MAX_LONG_STR_LEN=82

CONFIG_ZPL_MEMORY_PROFILING=y
CONFIG_ZPL_MEMORY_PROFILING_INTERVAL=10
CONFIG_ZPL_MEMORY_PROFILING_THREAD_PRIORITY=-1

CONFIG_CPU_LOAD=y
CONFIG_ZPL_CPU_LOAD_TRACE=y
CONFIG_ZPL_CPU_LOAD_PROFILING=y
CONFIG_ZPL_CPU_LOAD_PROFILING_INTERVAL=10
CONFIG_ZPL_CPU_LOAD_PROFILING_THREAD_PRIORITY=-1

CONFIG_ZPL_SCOPE_MARKING=y
