CONFIG_ZPL=y
CONFIG_ZPL_TRACE=y
CONFIG_ZPL_SCOPE_MARKING=y
CONFIG_ZPL_TVM_PROFILER=y
CONFIG_ZPL_TFLM_PROFILER=y
CONFIG_ZPL_TRACE_CTF_MAX_LONG_STR_LEN=82
CONFIG_ZPL_SAMPLE_TVM_HEAP_SIZE=64

CONFIG_SYS_HEAP_ARRAY_SIZE=4
CONFIG_ZPL_MEMORY_PROFILING=y
CONFIG_ZPL_MEMORY_PROFILING_INTERVAL=5
CONFIG_ZPL_MEMORY_PROFILING_THREAD_PRIORITY=-1

CONFIG_TRACING_BUFFER_SIZE=4096
CONFIG_TRACING_SYNC=y
CONFIG_MAIN_STACK_SIZE=3072

CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_TIMING_FUNCTIONS=y
CONFIG_ZEPHYR_TVM_MODULE=y
CONFIG_ZEPHYR_DLPACK_MODULE=y
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_ZPL_SAMPLE_TFLM_MODEL="sine;sine"
CONFIG_ZPL_SAMPLE_TVM_QUANTIZED_MODEL=y
CONFIG_CPP=y
CONFIG_STD_CPP17=y

CONFIG_LOG=y
CONFIG_ZPL_LOG_LEVEL_INF=y
