stages:
  - Test

.test_template: &test_template
  stage: Test
  variables:
    DEBIAN_FRONTEND: noninteractive
    CMAKE_PREFIX_PATH: /opt/toolchains
    RENODE_VERSION: "renode_1.15.3+20250611gitbf88af3a1_amd64.deb"
  image: "zephyrprojectrtos/ci:v0.27.5"
  before_script:
    - wget "https://dl.antmicro.com/projects/renode/builds/${RENODE_VERSION}" -O renode.deb
    - dpkg -i renode.deb
    - apt update -qq
    - apt install -yqq python3-bt2 xxd git-lfs gdb-multiarch
    - git lfs pull

Run Tuttest:
  extends: .test_template
  script:
    - pip install git+https://github.com/antmicro/tuttest
    - tuttest README.md "pip-init" | bash -
    - tuttest README.md "west-init" | bash -
    - tuttest README.md "build-samples" | bash -

Run Twister:
  extends: .test_template
  parallel:
    - qemu_cortex_m3
    - max78002evkit/max78002/m4
    - max32690fthr/max32690/m4
    - stm32f429i_disc1/stm32f429xx
  script:
    - source env.sh
    - west init -l .
    - west update
    - west patch apply
    - west zephyr-export
    - west twister -v -p ${CI_PARALLEL_NAME} -T samples -T tests
  artifacts:
    paths:
      - twister-out
    when: always

Run Lint:
  stage: Test
  image: "zephyrprojectrtos/ci:v0.27.5"
  script:
    - west init -l .
    - west update
    - west patch apply
    - west zephyr-export

    - excludes="-e SysbuildKconfig -e GitLint -e Identity -e ClangFormat -e BinaryFiles"
    - ../zephyr/scripts/ci/check_compliance.py -c origin/main $excludes
