stages:
  - Test

.test_template: &test_template
  stage: Test
  variables:
    DEBIAN_FRONTEND: noninteractive
    CMAKE_PREFIX_PATH: /opt/toolchains
    RENODE_VERSION: "renode_1.15.3+20250611gitbf88af3a1_amd64.deb"
  image: "zephyrprojectrtos/ci:v0.28.2"
  before_script:
    - wget -q "https://dl.antmicro.com/projects/renode/builds/${RENODE_VERSION}" -O renode.deb
    - dpkg -i renode.deb
    - apt update -qq
    - apt install -yqq python3-bt2 xxd git-lfs gdb-multiarch
    - git lfs pull
    # make bt2 visible in the venv that comes with the container
    - cp -r /usr/lib/python3/dist-packages/bt2 /opt/python/venv/lib/**/site-packages/

Run Tuttest:
  extends: .test_template
  script:
    - pip install git+https://github.com/antmicro/tuttest
    - tuttest README.md "pip-init" | bash -
    - tuttest README.md "west-init" | bash -
    - tuttest README.md "build-samples" | bash -

Run Twister:
  extends: .test_template
  parallel: 8
  script:
    - source env.sh
    - west init -l .
    - west update &> /dev/null
    - west patch apply
    - west zephyr-export

    - |
      platforms="
        -p qemu_cortex_m3
        -p max78002evkit/max78002/m4
        -p max32690fthr/max32690/m4
        -p stm32f429i_disc1/stm32f429xx
      "
    - west twister -v $platforms -T samples -T tests --subset $CI_NODE_INDEX/$CI_NODE_TOTAL -j 1
  artifacts:
    paths:
      - twister-out
    when: always

Run Lint:
  stage: Test
  image: "zephyrprojectrtos/ci:v0.28.2"
  script:
    - west init -l .
    - west update
    - west patch apply
    - west zephyr-export

    - excludes="-e SysbuildKconfig -e GitLint -e Identity -e ClangFormat -e BinaryFiles"
    - ../zephyr/scripts/ci/check_compliance.py -c origin/main..HEAD $excludes
