line-length = 100
target-version = "py310"
preview = true

[lint]
select = [
    "I",      # enable isort
    "D",      # docstring errors
    "E",      # PEP8 errors
    "E261",   # At least two spaces before inline comment
    "E225",   # Missing whitespace around operator
    "F",      # PEP8 warnings
    "RUF100", # disallowed unnecessary noqa
]

ignore = [
    "E203",  # Whitespace before ':'
    "D105",  # Missing docstring in magic method
    "D203",  # 1 blank line required before class
    "D204",  # 1 blank line required after class docstring
    "D205",  # 1 blank line required between summary line and description
    "D212",  # Multi-line docstring summary should start at the first line
    "D200",  # One-line docstring should fit on one line
    "D102",  # Missing docstring in public method
    "D401",  # First line of docstring should be in imperative mood
    "D407",  # Missing argument description in the docstring (handled by pydoclint)
    "D413",  # Missing blank line after last section
]

[format]
line-ending = "lf"
