manifest:
  group-filter: [+optional]
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: antmicro
      url-base: https://github.com/antmicro
    - name: apache
      url-base: https://github.com/apache
    - name: dmlc
      url-base: https://github.com/dmlc

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: b64a56362d8bffbf33a3ec26b38315d9d35abac8
      import:
        name-allowlist:
          - cmsis
          - hal_adi
          - hal_stm32
          - tflite-micro
    - name: tvm
      remote: apache
      revision: v0.18.0
    - name: dlpack
      remote: dmlc
      revision: main
