manifest:
  self:
    west-commands: west/west-commands.yml

  group-filter: [+optional]
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: antmicro
      url-base: https://github.com/antmicro
    - name: apache
      url-base: https://github.com/apache
    - name: dmlc
      url-base: https://github.com/dmlc

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 4852719f98b3bac9c05196d9855d897f47e3c82f
      import:
        name-allowlist:
          - cmsis_6
          - hal_adi
          - hal_stm32
          - tflite-micro
    - name: tvm
      remote: apache
      revision: v0.18.0
    - name: dlpack
      remote: dmlc
      revision: main
