manifest:
  self:
    west-commands: west/west-commands.yml

  group-filter: [+optional]
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: antmicro
      url-base: https://github.com/antmicro
    - name: apache
      url-base: https://github.com/apache
    - name: dmlc
      url-base: https://github.com/dmlc

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: d41716f63c5c86c811e06559c25a668a9beb1d5a
      import:
        name-allowlist:
          - cmsis_6
          - hal_adi
          - hal_stm32
          - tflite-micro
    - name: tvm
      remote: apache
      revision: v0.18.0
    - name: dlpack
      remote: dmlc
      revision: main
