CONFIG_ZPL=y
CONFIG_ZPL_TRACE=y
CONFIG_ZPL_CONFIGURABLE_TIMESTAMP_CLOCK=y
CONFIG_ZPL_TFLM_PROFILER=y
CONFIG_ZPL_TRACE_FORMAT_CTF=y
CONFIG_ZPL_SAMPLE_TFLM_MODEL="audio_preprocessor_int8"
CONFIG_PRINTK=y

CONFIG_SYS_HEAP_ARRAY_SIZE=4

CONFIG_BOOT_BANNER=n

CONFIG_TRACING_BUFFER_SIZE=4096
CONFIG_TRACING_SYNC=y
CONFIG_MAIN_STACK_SIZE=3072

CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_ZPL_SAMPLE_TFLM_BUFFER_SIZE=20
CONFIG_CPP=y
CONFIG_STD_CPP17=y

CONFIG_LOG=y
CONFIG_ZPL_LOG_LEVEL_INF=y
