name: zephelin
run-name: Zephelin
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  RENODE_VERSION: "renode_1.16.0+20250929gitc16006c94_amd64.deb"
  DEBIAN_FRONTEND: noninteractive
  CMAKE_PREFIX_PATH: /opt/toolchains

jobs:
  Run-Tuttest:
    runs-on: ubuntu-22.04
    steps:
      - name: Free space on runner
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ggc
          sudo rm -rf /usr/local/.ghcup
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          ./scripts/ci/install_deps.sh
          pip install git+https://github.com/antmicro/tuttest
      - name: Run Tuttest
        run: |
          python3 -m venv venv
          source venv/bin/activate
          tuttest README.md "pip-init" | bash -
          tuttest README.md "west-init" | bash -
          tuttest README.md "build-samples" | bash -
          tuttest README.md "renode-prepare" | bash -
          tuttest README.md "build-demo" | bash -

  Run-Twister:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - qemu_cortex_m3
          - max78002evkit/max78002/m4
          - stm32f429i_disc1/stm32f429xx
          - mpfs_icicle/polarfire/u54/smp
          - max32650fthr
    steps:
      - name: Free space on runner
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ggc
          sudo rm -rf /usr/local/.ghcup
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          ./scripts/ci/install_deps.sh
      - name: Setup Zephyr
        run: |
          ./scripts/ci/setup_zephyr.sh
      - name: Run Twister
        run: |
          export ZPL_BASE="$(pwd)"
          west twister -v -p ${{ matrix.platform }} -T samples -T tests -j 1 --timeout-multiplier 3
          normalized_name=$(echo ${{ matrix.platform}} | tr '/' '_')
          echo "TWISTER_SUFFIX=$normalized_name" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "twister-out-${{ env.TWISTER_SUFFIX }}"
          path: |
              twister-out

  Run-Lint:
    runs-on: ubuntu-22.04
    env:
      BASE_REF: ${{ github.base_ref || 'main' }}
    steps:
      - name: Free space on runner
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ggc
          sudo rm -rf /usr/local/.ghcup
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          ./scripts/ci/install_deps.sh
      - name: Setup Zephyr
        run: |
          ./scripts/ci/setup_zephyr.sh
      - name: Run Compliance Check
        run: |
          git config --global --add safe.directory $(pwd)
          excludes="-e SysbuildKconfig -e GitLint -e Identity -e ClangFormat -e BinaryFiles"
          ../zephyr/scripts/ci/check_compliance.py $excludes -c origin/${BASE_REF}..

  Run-PyTest:
    runs-on: ubuntu-22.04
    steps:
      - name: Free space on runner
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ggc
          sudo rm -rf /usr/local/.ghcup
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          ./scripts/ci/install_deps.sh
      - name: Setup Zephyr
        run: |
          ./scripts/ci/setup_zephyr.sh
      - name: Install PyTest
        run: |
          pip install --no-cache-dir pytest -r requirements.txt -r tests/requirements.txt
      - run: |
          pytest

  Run-PrepareTrace:
    runs-on: ubuntu-22.04
    steps:
      - name: Free space on runner
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ggc
          sudo rm -rf /usr/local/.ghcup
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          ./scripts/ci/install_deps.sh
      - name: Setup Zephyr
        run: |
          ./scripts/ci/setup_zephyr.sh
      - name: Install PyTest
        run: |
          pip install --no-cache-dir  pytest -r requirements.txt
      - name: Run PrepareTrace
        run: |
          python ./scripts/prepare_trace.py tests/ctf2tef/trace.ctf -o trace.tef
          diff tests/ctf2tef/trace.tef trace.tef
      - uses: actions/upload-artifact@v4
        with:
          path: |
              trace.def
